export const data = {
  schema: {
    models: {
      Notice: {
        doits: {
          delete: {
            details: {},
          },
          create: {
            details: {
              set: {
                title: "string",
                "lead?": "string",
                text: "string",
                siteId: "string",
                role: "'Master' | 'OrganizationHead' | 'FinanceHead' | 'Expert' | 'UnitHead' | 'UnitEmployee' | 'UniversityHead' | 'StoreHead' | 'Supplier' | 'StockClerk' | 'Accountant'",
              },
              receiver: {
                "unitsId?": ["string"],
                "organizationsId?": ["string"],
                "universitiesId?": ["string"],
                "usersId?": ["string"],
              },
            },
          },
          get: {
            details: {},
          },
        },
      },
      Brand: {
        doits: {
          update: {
            details: {},
          },
          delete: {
            details: {},
          },
          create: {
            details: {
              set: {
                name: "string",
                enName: "string",
                manufactureId: "string",
              },
            },
          },
          get: {
            details: {},
          },
        },
      },
      ContactUs: {
        doits: {
          update: {
            details: {},
          },
          delete: {
            details: {},
          },
          create: {
            details: {},
          },
          get: {
            details: {},
          },
        },
      },
      Unit: {
        doits: {
          update: {
            details: {},
          },
          delete: {
            details: {},
          },
          create: {
            details: {},
          },
          get: {
            details: {},
          },
        },
      },
      Department: {
        doits: {
          get: {
            details: {},
          },
          update: {
            details: {},
          },
          delete: {
            details: {},
          },
          create: {
            details: {},
          },
        },
      },
      BlogCategory: {
        doits: {
          create: {
            details: {},
          },
          delete: {
            details: {},
          },
        },
      },
      BlogTag: {
        doits: {
          delete: {
            details: {},
          },
          create: {
            details: {},
          },
        },
      },
      Manufacture: {
        doits: {
          update: {
            details: {},
          },
          delete: {
            details: {},
          },
          create: {
            details: {},
          },
          get: {
            details: {},
          },
        },
      },
      Store: {
        doits: {
          registerRequest: {
            details: {},
          },
          registerRequestVerification: {
            details: {},
          },
        },
      },
      Organization: {
        doits: {
          update: {
            details: {},
          },
          delete: {
            details: {},
          },
          create: {
            details: {},
          },
          get: {
            details: {},
          },
        },
      },
      University: {
        doits: {
          get: {
            details: {},
          },
          update: {
            details: {},
          },
          create: {
            details: {},
          },
          delete: {
            details: {},
          },
        },
      },
      Ware: {
        doits: {
          create: {
            details: {
              set: {
                name: "string",
                enName: "string",
                "price?": "number",
                "irc?": "number",
                "umdns?": "number",
                "gtin?": "number",
                brandId: "string",
                wareTypeId: "string",
                wareClassId: "string",
                wareGroupId: "string",
                wareModelId: "string",
                "photoUrl?": "string",
              },
              "get?": {
                "_id?": "0 | 1",
                "createAt?": "0 | 1",
                "updateAt?": "0 | 1",
                "name?": "0 | 1",
                "enName?": "0 | 1",
                "brand?": "0 | 1",
                "price?": "0 | 1",
                "manufactureName?": "0 | 1",
                "orderedNumber?": "0 | 1",
                "iric?": "0 | 1",
                "umdns?": "0 | 1",
                "gtn?": "0 | 1",
                "photoUrl?": "0 | 1",
                "wareModel?": {
                  "_id?": "0 | 1",
                  "createAt?": "0 | 1",
                  "updateAt?": "0 | 1",
                  "name?": "0 | 1",
                  "enName?": "0 | 1",
                  "wareType?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                  },
                  "wareClass?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                    "wareTypeId?": "0 | 1",
                  },
                  "wareGroup?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                    "wareTypeId?": "0 | 1",
                  },
                  "wares?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                    "brand?": "0 | 1",
                    "price?": "0 | 1",
                    "manufactureName?": "0 | 1",
                    "orderedNumber?": "0 | 1",
                    "iric?": "0 | 1",
                    "umdns?": "0 | 1",
                    "gtn?": "0 | 1",
                    "photoUrl?": "0 | 1",
                  },
                  "inventories?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "availableLongPayment?": "0 | 1",
                    "expiration?": "0 | 1",
                    "inventoryNo?": "0 | 1",
                    "barcode?": "0 | 1",
                    "qrc?": "0 | 1",
                    "isBarcodeSet?": "0 | 1",
                    "isQrcSet?": "0 | 1",
                    "isExpirationNear?": "0 | 1",
                    "hasAbsolutePrice?": "0 | 1",
                    "pricePercentage?": "0 | 1",
                    "price?": "0 | 1",
                    "monthPrice?": "0 | 1",
                    "monthPercent?": "0 | 1",
                  },
                  "orders?": {},
                  "stores?": {},
                  "creator?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "location?": "0 | 1",
                    "address?": "0 | 1",
                    "contact?": "0 | 1",
                    "postalCode?": "0 | 1",
                    "phoneNumber?": "0 | 1",
                    "email?": "0 | 1",
                    "gender?": "0 | 1",
                    "birthDate?": "0 | 1",
                    "nationalIdCardUrl?": "0 | 1",
                    "ssn?": "0 | 1",
                    "photoUrl?": "0 | 1",
                    "firstName?": "0 | 1",
                    "lastName?": "0 | 1",
                    "devices?": "0 | 1",
                    "password?": "0 | 1",
                    "isActive?": "0 | 1",
                  },
                },
                "wareGroup?": {
                  "_id?": "0 | 1",
                  "createAt?": "0 | 1",
                  "updateAt?": "0 | 1",
                  "name?": "0 | 1",
                  "enName?": "0 | 1",
                  "wareTypeId?": "0 | 1",
                  "wareType?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                  },
                  "wareClasses?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                    "wareTypeId?": "0 | 1",
                  },
                  "wareModels?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                  },
                  "wares?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                    "brand?": "0 | 1",
                    "price?": "0 | 1",
                    "manufactureName?": "0 | 1",
                    "orderedNumber?": "0 | 1",
                    "iric?": "0 | 1",
                    "umdns?": "0 | 1",
                    "gtn?": "0 | 1",
                    "photoUrl?": "0 | 1",
                  },
                  "inventories?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "availableLongPayment?": "0 | 1",
                    "expiration?": "0 | 1",
                    "inventoryNo?": "0 | 1",
                    "barcode?": "0 | 1",
                    "qrc?": "0 | 1",
                    "isBarcodeSet?": "0 | 1",
                    "isQrcSet?": "0 | 1",
                    "isExpirationNear?": "0 | 1",
                    "hasAbsolutePrice?": "0 | 1",
                    "pricePercentage?": "0 | 1",
                    "price?": "0 | 1",
                    "monthPrice?": "0 | 1",
                    "monthPercent?": "0 | 1",
                  },
                  "orders?": {},
                },
                "wareClass?": {
                  "_id?": "0 | 1",
                  "createAt?": "0 | 1",
                  "updateAt?": "0 | 1",
                  "name?": "0 | 1",
                  "enName?": "0 | 1",
                  "wareTypeId?": "0 | 1",
                  "wareType?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                  },
                  "wareClasses?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                    "wareTypeId?": "0 | 1",
                  },
                  "wareModels?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                  },
                  "wares?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                    "brand?": "0 | 1",
                    "price?": "0 | 1",
                    "manufactureName?": "0 | 1",
                    "orderedNumber?": "0 | 1",
                    "iric?": "0 | 1",
                    "umdns?": "0 | 1",
                    "gtn?": "0 | 1",
                    "photoUrl?": "0 | 1",
                  },
                  "inventories?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "availableLongPayment?": "0 | 1",
                    "expiration?": "0 | 1",
                    "inventoryNo?": "0 | 1",
                    "barcode?": "0 | 1",
                    "qrc?": "0 | 1",
                    "isBarcodeSet?": "0 | 1",
                    "isQrcSet?": "0 | 1",
                    "isExpirationNear?": "0 | 1",
                    "hasAbsolutePrice?": "0 | 1",
                    "pricePercentage?": "0 | 1",
                    "price?": "0 | 1",
                    "monthPrice?": "0 | 1",
                    "monthPercent?": "0 | 1",
                  },
                  "orders?": {},
                },
                "wareType?": {
                  "_id?": "0 | 1",
                  "createAt?": "0 | 1",
                  "updateAt?": "0 | 1",
                  "name?": "0 | 1",
                  "enName?": "0 | 1",
                  "wareClasses?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                    "wareTypeId?": "0 | 1",
                  },
                  "wareGroups?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                    "wareTypeId?": "0 | 1",
                  },
                  "wareModels?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                  },
                  "wares?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                    "brand?": "0 | 1",
                    "price?": "0 | 1",
                    "manufactureName?": "0 | 1",
                    "orderedNumber?": "0 | 1",
                    "iric?": "0 | 1",
                    "umdns?": "0 | 1",
                    "gtn?": "0 | 1",
                    "photoUrl?": "0 | 1",
                  },
                  "inventories?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "availableLongPayment?": "0 | 1",
                    "expiration?": "0 | 1",
                    "inventoryNo?": "0 | 1",
                    "barcode?": "0 | 1",
                    "qrc?": "0 | 1",
                    "isBarcodeSet?": "0 | 1",
                    "isQrcSet?": "0 | 1",
                    "isExpirationNear?": "0 | 1",
                    "hasAbsolutePrice?": "0 | 1",
                    "pricePercentage?": "0 | 1",
                    "price?": "0 | 1",
                    "monthPrice?": "0 | 1",
                    "monthPercent?": "0 | 1",
                  },
                  "orders?": {},
                  "offers?": {},
                  "stores?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "ceoName?": "0 | 1",
                    "cityDeliveryTime?": "0 | 1",
                    "availableFastDeliveryTime?": "0 | 1",
                    "stateDeliveryTime?": "0 | 1",
                    "selectedStateDeliveryTime?": "0 | 1",
                    "countryDeliveryTime?": "0 | 1",
                    "score?": "0 | 1",
                    "totalSoldAmount?": "0 | 1",
                    "totalSoldNumber?": "0 | 1",
                    "totalPaid?": "0 | 1",
                    "totalNotPaid?": "0 | 1",
                    "paymentDeadLine?": "0 | 1",
                    "serviceRange?": "0 | 1",
                    "fastDelivery?": "0 | 1",
                    "isAvailableInHolidays?": "0 | 1",
                    "status?": "0 | 1",
                    "updateStatusDescription?": "0 | 1",
                  },
                },
                "manufacture?": {
                  "_id?": "0 | 1",
                  "createAt?": "0 | 1",
                  "updateAt?": "0 | 1",
                  "name?": "0 | 1",
                  "enName?": "0 | 1",
                  "country?": "0 | 1",
                },
                "inventories?": {
                  "_id?": "0 | 1",
                  "createAt?": "0 | 1",
                  "updateAt?": "0 | 1",
                  "availableLongPayment?": "0 | 1",
                  "expiration?": "0 | 1",
                  "inventoryNo?": "0 | 1",
                  "barcode?": "0 | 1",
                  "qrc?": "0 | 1",
                  "isBarcodeSet?": "0 | 1",
                  "isQrcSet?": "0 | 1",
                  "isExpirationNear?": "0 | 1",
                  "hasAbsolutePrice?": "0 | 1",
                  "pricePercentage?": "0 | 1",
                  "price?": "0 | 1",
                  "monthPrice?": "0 | 1",
                  "monthPercent?": "0 | 1",
                  "ware?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                    "brand?": "0 | 1",
                    "price?": "0 | 1",
                    "manufactureName?": "0 | 1",
                    "orderedNumber?": "0 | 1",
                    "iric?": "0 | 1",
                    "umdns?": "0 | 1",
                    "gtn?": "0 | 1",
                    "photoUrl?": "0 | 1",
                  },
                  "store?": {},
                  "orders?": {},
                  "wareType?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                  },
                  "wareGroup?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                    "wareTypeId?": "0 | 1",
                  },
                  "wareClass?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                    "wareTypeId?": "0 | 1",
                  },
                  "wareModel?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                  },
                },
                "orders?": {},
              },
            },
          },
          update: {
            details: {
              set: {
                _id: "string",
                "name?": "string",
                "enName?": "string",
                "price?": "number",
                "irc?": "number",
                "umdns?": "number",
                "gtin?": "number",
                "brandId?": "string",
                "wareTypeId?": "string",
                "wareClassId?": "string",
                "wareGroupId?": "string",
                "wareModelId?": "string",
                "photoUrl?": "string",
              },
              "get?": {
                "_id?": "0 | 1",
                "createAt?": "0 | 1",
                "updateAt?": "0 | 1",
                "name?": "0 | 1",
                "enName?": "0 | 1",
                "brand?": "0 | 1",
                "price?": "0 | 1",
                "manufactureName?": "0 | 1",
                "orderedNumber?": "0 | 1",
                "iric?": "0 | 1",
                "umdns?": "0 | 1",
                "gtn?": "0 | 1",
                "photoUrl?": "0 | 1",
                "wareModel?": {
                  "_id?": "0 | 1",
                  "createAt?": "0 | 1",
                  "updateAt?": "0 | 1",
                  "name?": "0 | 1",
                  "enName?": "0 | 1",
                },
                "wareGroup?": {
                  "_id?": "0 | 1",
                  "createAt?": "0 | 1",
                  "updateAt?": "0 | 1",
                  "name?": "0 | 1",
                  "enName?": "0 | 1",
                  "wareTypeId?": "0 | 1",
                },
                "wareClass?": {
                  "_id?": "0 | 1",
                  "createAt?": "0 | 1",
                  "updateAt?": "0 | 1",
                  "name?": "0 | 1",
                  "enName?": "0 | 1",
                  "wareTypeId?": "0 | 1",
                },
                "wareType?": {
                  "_id?": "0 | 1",
                  "createAt?": "0 | 1",
                  "updateAt?": "0 | 1",
                  "name?": "0 | 1",
                  "enName?": "0 | 1",
                },
                "manufacture?": {
                  "_id?": "0 | 1",
                  "createAt?": "0 | 1",
                  "updateAt?": "0 | 1",
                  "name?": "0 | 1",
                  "enName?": "0 | 1",
                  "country?": "0 | 1",
                },
                "inventories?": {
                  "_id?": "0 | 1",
                  "createAt?": "0 | 1",
                  "updateAt?": "0 | 1",
                  "availableLongPayment?": "0 | 1",
                  "expiration?": "0 | 1",
                  "inventoryNo?": "0 | 1",
                  "barcode?": "0 | 1",
                  "qrc?": "0 | 1",
                  "isBarcodeSet?": "0 | 1",
                  "isQrcSet?": "0 | 1",
                  "isExpirationNear?": "0 | 1",
                  "hasAbsolutePrice?": "0 | 1",
                  "pricePercentage?": "0 | 1",
                  "price?": "0 | 1",
                  "monthPrice?": "0 | 1",
                  "monthPercent?": "0 | 1",
                },
                "orders?": {},
              },
            },
          },
          get: {
            details: {},
          },
          delete: {
            details: {},
          },
        },
      },
      City: {
        doits: {
          update: {
            details: {},
          },
          delete: {
            details: {},
          },
          create: {
            details: {
              set: {
                name: "string",
                enName: "string",
                stateId: "string",
                "geometries?": ["string"],
              },
              "get?": {
                "_id?": "0 | 1",
                "createAt?": "0 | 1",
                "updateAt?": "0 | 1",
                "name?": "0 | 1",
                "enName?": "0 | 1",
                "state?": {
                  "_id?": "0 | 1",
                  "createAt?": "0 | 1",
                  "updateAt?": "0 | 1",
                  "name?": "0 | 1",
                  "enName?": "0 | 1",
                },
                "universities?": {
                  "_id?": "0 | 1",
                  "createAt?": "0 | 1",
                  "updateAt?": "0 | 1",
                  "name?": "0 | 1",
                  "organizations?": {
                    "acceptedByOrgHeadNumber?": "0 | 1",
                    "rejectedByOrgHeadNumber?": "0 | 1",
                    "pendingInOrgHeadNumber?": "0 | 1",
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "location?": "0 | 1",
                    "address?": "0 | 1",
                    "contact?": "0 | 1",
                    "postalCode?": "0 | 1",
                    "logoUrl?": "0 | 1",
                    "name?": "0 | 1",
                  },
                  "universityHead?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "location?": "0 | 1",
                    "address?": "0 | 1",
                    "contact?": "0 | 1",
                    "postalCode?": "0 | 1",
                    "phoneNumber?": "0 | 1",
                    "email?": "0 | 1",
                    "gender?": "0 | 1",
                    "birthDate?": "0 | 1",
                    "nationalIdCardUrl?": "0 | 1",
                    "ssn?": "0 | 1",
                    "photoUrl?": "0 | 1",
                    "firstName?": "0 | 1",
                    "lastName?": "0 | 1",
                    "devices?": "0 | 1",
                    "password?": "0 | 1",
                    "isActive?": "0 | 1",
                  },
                  "city?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                  },
                },
                "stores?": {},
                "organizations?": {
                  "acceptedByOrgHeadNumber?": "0 | 1",
                  "rejectedByOrgHeadNumber?": "0 | 1",
                  "pendingInOrgHeadNumber?": "0 | 1",
                  "_id?": "0 | 1",
                  "createAt?": "0 | 1",
                  "updateAt?": "0 | 1",
                  "location?": "0 | 1",
                  "address?": "0 | 1",
                  "contact?": "0 | 1",
                  "postalCode?": "0 | 1",
                  "logoUrl?": "0 | 1",
                  "name?": "0 | 1",
                },
              },
            },
          },
          get: {
            details: {},
          },
        },
      },
      Country: {
        doits: {
          update: {
            details: {},
          },
          delete: {
            details: {},
          },
          create: {
            details: {},
          },
          get: {
            details: {
              set: {
                "pagination?": {
                  "lastObjectId?": "string",
                  "limit?": "number",
                  "page?": "number",
                },
                "sort?": {
                  "name?": "1 | -1",
                  "_id?": "1 | -1",
                  "enName?": "1 | -1",
                  "geometries?": "1 | -1",
                },
                "_id?": "string",
                "name?": "string",
                "enName?": "string",
              },
              "get?": {
                "_id?": "0 | 1",
                "createAt?": "0 | 1",
                "updateAt?": "0 | 1",
                "name?": "0 | 1",
                "enName?": "0 | 1",
                "states?": {
                  "_id?": "0 | 1",
                  "createAt?": "0 | 1",
                  "updateAt?": "0 | 1",
                  "name?": "0 | 1",
                  "enName?": "0 | 1",
                  "cities?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                    "state?": {
                      "_id?": "0 | 1",
                      "createAt?": "0 | 1",
                      "updateAt?": "0 | 1",
                      "name?": "0 | 1",
                      "enName?": "0 | 1",
                    },
                    "universities?": {
                      "_id?": "0 | 1",
                      "createAt?": "0 | 1",
                      "updateAt?": "0 | 1",
                      "name?": "0 | 1",
                      "organizations?": {
                        "acceptedByOrgHeadNumber?": "0 | 1",
                        "rejectedByOrgHeadNumber?": "0 | 1",
                        "pendingInOrgHeadNumber?": "0 | 1",
                        "_id?": "0 | 1",
                        "createAt?": "0 | 1",
                        "updateAt?": "0 | 1",
                        "location?": "0 | 1",
                        "address?": "0 | 1",
                        "contact?": "0 | 1",
                        "postalCode?": "0 | 1",
                        "logoUrl?": "0 | 1",
                        "name?": "0 | 1",
                      },
                      "universityHead?": {
                        "_id?": "0 | 1",
                        "createAt?": "0 | 1",
                        "updateAt?": "0 | 1",
                        "location?": "0 | 1",
                        "address?": "0 | 1",
                        "contact?": "0 | 1",
                        "postalCode?": "0 | 1",
                        "phoneNumber?": "0 | 1",
                        "email?": "0 | 1",
                        "gender?": "0 | 1",
                        "birthDate?": "0 | 1",
                        "nationalIdCardUrl?": "0 | 1",
                        "ssn?": "0 | 1",
                        "photoUrl?": "0 | 1",
                        "firstName?": "0 | 1",
                        "lastName?": "0 | 1",
                        "devices?": "0 | 1",
                        "password?": "0 | 1",
                        "isActive?": "0 | 1",
                      },
                      "city?": {
                        "_id?": "0 | 1",
                        "createAt?": "0 | 1",
                        "updateAt?": "0 | 1",
                        "name?": "0 | 1",
                        "enName?": "0 | 1",
                      },
                    },
                    "stores?": {},
                    "organizations?": {
                      "acceptedByOrgHeadNumber?": "0 | 1",
                      "rejectedByOrgHeadNumber?": "0 | 1",
                      "pendingInOrgHeadNumber?": "0 | 1",
                      "_id?": "0 | 1",
                      "createAt?": "0 | 1",
                      "updateAt?": "0 | 1",
                      "location?": "0 | 1",
                      "address?": "0 | 1",
                      "contact?": "0 | 1",
                      "postalCode?": "0 | 1",
                      "logoUrl?": "0 | 1",
                      "name?": "0 | 1",
                    },
                  },
                  "universities?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "organizations?": {
                      "acceptedByOrgHeadNumber?": "0 | 1",
                      "rejectedByOrgHeadNumber?": "0 | 1",
                      "pendingInOrgHeadNumber?": "0 | 1",
                      "_id?": "0 | 1",
                      "createAt?": "0 | 1",
                      "updateAt?": "0 | 1",
                      "location?": "0 | 1",
                      "address?": "0 | 1",
                      "contact?": "0 | 1",
                      "postalCode?": "0 | 1",
                      "logoUrl?": "0 | 1",
                      "name?": "0 | 1",
                      "users?": {
                        "_id?": "0 | 1",
                        "createAt?": "0 | 1",
                        "updateAt?": "0 | 1",
                        "location?": "0 | 1",
                        "address?": "0 | 1",
                        "contact?": "0 | 1",
                        "postalCode?": "0 | 1",
                        "phoneNumber?": "0 | 1",
                        "email?": "0 | 1",
                        "gender?": "0 | 1",
                        "birthDate?": "0 | 1",
                        "nationalIdCardUrl?": "0 | 1",
                        "ssn?": "0 | 1",
                        "photoUrl?": "0 | 1",
                        "firstName?": "0 | 1",
                        "lastName?": "0 | 1",
                        "devices?": "0 | 1",
                        "password?": "0 | 1",
                        "isActive?": "0 | 1",
                      },
                      "notices?": {
                        "_id?": "0 | 1",
                        "createAt?": "0 | 1",
                        "updateAt?": "0 | 1",
                        "title?": "0 | 1",
                        "lead?": "0 | 1",
                        "text?": "0 | 1",
                        "pic?": "0 | 1",
                        "files?": "0 | 1",
                      },
                      "userHead?": {
                        "_id?": "0 | 1",
                        "createAt?": "0 | 1",
                        "updateAt?": "0 | 1",
                        "title?": "0 | 1",
                        "lead?": "0 | 1",
                        "text?": "0 | 1",
                        "pic?": "0 | 1",
                        "files?": "0 | 1",
                      },
                      "orders?": {
                        "_id?": "0 | 1",
                        "createAt?": "0 | 1",
                        "updateAt?": "0 | 1",
                        "status?": "0 | 1",
                        "num?": "0 | 1",
                        "remaining?": "0 | 1",
                        "stockRemaining?": "0 | 1",
                        "totalPrice?": "0 | 1",
                        "deliveryTime?": "0 | 1",
                        "isExpirationNear?": "0 | 1",
                        "fastDeliveryTime?": "0 | 1",
                        "paymentBudget?": "0 | 1",
                        "fastDelivery?": "0 | 1",
                        "trackingcode?": "0 | 1",
                        "selectedProduct?": "0 | 1",
                        "chosenPayment?": "0 | 1",
                        "longPayment?": "0 | 1",
                      },
                      "departments?": {
                        "_id?": "0 | 1",
                        "createAt?": "0 | 1",
                        "updateAt?": "0 | 1",
                        "acceptedByOrgHeadNumber?": "0 | 1",
                        "rejectedByOrgHeadNumber?": "0 | 1",
                        "pendingInOrgHeadNumber?": "0 | 1",
                        "name?": "0 | 1",
                        "enName?": "0 | 1",
                      },
                      "university?": {
                        "_id?": "0 | 1",
                        "createAt?": "0 | 1",
                        "updateAt?": "0 | 1",
                        "name?": "0 | 1",
                        "organizations?": {
                          "acceptedByOrgHeadNumber?": "0 | 1",
                          "rejectedByOrgHeadNumber?": "0 | 1",
                          "pendingInOrgHeadNumber?": "0 | 1",
                          "_id?": "0 | 1",
                          "createAt?": "0 | 1",
                          "updateAt?": "0 | 1",
                          "location?": "0 | 1",
                          "address?": "0 | 1",
                          "contact?": "0 | 1",
                          "postalCode?": "0 | 1",
                          "logoUrl?": "0 | 1",
                          "name?": "0 | 1",
                        },
                        "universityHead?": {
                          "_id?": "0 | 1",
                          "createAt?": "0 | 1",
                          "updateAt?": "0 | 1",
                          "location?": "0 | 1",
                          "address?": "0 | 1",
                          "contact?": "0 | 1",
                          "postalCode?": "0 | 1",
                          "phoneNumber?": "0 | 1",
                          "email?": "0 | 1",
                          "gender?": "0 | 1",
                          "birthDate?": "0 | 1",
                          "nationalIdCardUrl?": "0 | 1",
                          "ssn?": "0 | 1",
                          "photoUrl?": "0 | 1",
                          "firstName?": "0 | 1",
                          "lastName?": "0 | 1",
                          "devices?": "0 | 1",
                          "password?": "0 | 1",
                          "isActive?": "0 | 1",
                        },
                        "city?": {
                          "_id?": "0 | 1",
                          "createAt?": "0 | 1",
                          "updateAt?": "0 | 1",
                          "name?": "0 | 1",
                          "enName?": "0 | 1",
                        },
                      },
                      "allowedWareModels?": {
                        "_id?": "0 | 1",
                        "createAt?": "0 | 1",
                        "updateAt?": "0 | 1",
                        "name?": "0 | 1",
                        "enName?": "0 | 1",
                      },
                      "employees?": {
                        "_id?": "0 | 1",
                        "createAt?": "0 | 1",
                        "updateAt?": "0 | 1",
                        "location?": "0 | 1",
                        "address?": "0 | 1",
                        "contact?": "0 | 1",
                        "postalCode?": "0 | 1",
                        "phoneNumber?": "0 | 1",
                        "email?": "0 | 1",
                        "gender?": "0 | 1",
                        "birthDate?": "0 | 1",
                        "nationalIdCardUrl?": "0 | 1",
                        "ssn?": "0 | 1",
                        "photoUrl?": "0 | 1",
                        "firstName?": "0 | 1",
                        "lastName?": "0 | 1",
                        "devices?": "0 | 1",
                        "password?": "0 | 1",
                        "isActive?": "0 | 1",
                      },
                      "stockClerks?": {
                        "_id?": "0 | 1",
                        "createAt?": "0 | 1",
                        "updateAt?": "0 | 1",
                        "location?": "0 | 1",
                        "address?": "0 | 1",
                        "contact?": "0 | 1",
                        "postalCode?": "0 | 1",
                        "phoneNumber?": "0 | 1",
                        "email?": "0 | 1",
                        "gender?": "0 | 1",
                        "birthDate?": "0 | 1",
                        "nationalIdCardUrl?": "0 | 1",
                        "ssn?": "0 | 1",
                        "photoUrl?": "0 | 1",
                        "firstName?": "0 | 1",
                        "lastName?": "0 | 1",
                        "devices?": "0 | 1",
                        "password?": "0 | 1",
                        "isActive?": "0 | 1",
                      },
                      "experts?": {
                        "_id?": "0 | 1",
                        "createAt?": "0 | 1",
                        "updateAt?": "0 | 1",
                        "location?": "0 | 1",
                        "address?": "0 | 1",
                        "contact?": "0 | 1",
                        "postalCode?": "0 | 1",
                        "phoneNumber?": "0 | 1",
                        "email?": "0 | 1",
                        "gender?": "0 | 1",
                        "birthDate?": "0 | 1",
                        "nationalIdCardUrl?": "0 | 1",
                        "ssn?": "0 | 1",
                        "photoUrl?": "0 | 1",
                        "firstName?": "0 | 1",
                        "lastName?": "0 | 1",
                        "devices?": "0 | 1",
                        "password?": "0 | 1",
                        "isActive?": "0 | 1",
                      },
                      "suppliers?": {
                        "_id?": "0 | 1",
                        "createAt?": "0 | 1",
                        "updateAt?": "0 | 1",
                        "location?": "0 | 1",
                        "address?": "0 | 1",
                        "contact?": "0 | 1",
                        "postalCode?": "0 | 1",
                        "phoneNumber?": "0 | 1",
                        "email?": "0 | 1",
                        "gender?": "0 | 1",
                        "birthDate?": "0 | 1",
                        "nationalIdCardUrl?": "0 | 1",
                        "ssn?": "0 | 1",
                        "photoUrl?": "0 | 1",
                        "firstName?": "0 | 1",
                        "lastName?": "0 | 1",
                        "devices?": "0 | 1",
                        "password?": "0 | 1",
                        "isActive?": "0 | 1",
                      },
                      "financeHead?": {
                        "_id?": "0 | 1",
                        "createAt?": "0 | 1",
                        "updateAt?": "0 | 1",
                        "location?": "0 | 1",
                        "address?": "0 | 1",
                        "contact?": "0 | 1",
                        "postalCode?": "0 | 1",
                        "phoneNumber?": "0 | 1",
                        "email?": "0 | 1",
                        "gender?": "0 | 1",
                        "birthDate?": "0 | 1",
                        "nationalIdCardUrl?": "0 | 1",
                        "ssn?": "0 | 1",
                        "photoUrl?": "0 | 1",
                        "firstName?": "0 | 1",
                        "lastName?": "0 | 1",
                        "devices?": "0 | 1",
                        "password?": "0 | 1",
                        "isActive?": "0 | 1",
                      },
                      "organizationHead?": {
                        "_id?": "0 | 1",
                        "createAt?": "0 | 1",
                        "updateAt?": "0 | 1",
                        "location?": "0 | 1",
                        "address?": "0 | 1",
                        "contact?": "0 | 1",
                        "postalCode?": "0 | 1",
                        "phoneNumber?": "0 | 1",
                        "email?": "0 | 1",
                        "gender?": "0 | 1",
                        "birthDate?": "0 | 1",
                        "nationalIdCardUrl?": "0 | 1",
                        "ssn?": "0 | 1",
                        "photoUrl?": "0 | 1",
                        "firstName?": "0 | 1",
                        "lastName?": "0 | 1",
                        "devices?": "0 | 1",
                        "password?": "0 | 1",
                        "isActive?": "0 | 1",
                      },
                    },
                    "universityHead?": {
                      "_id?": "0 | 1",
                      "createAt?": "0 | 1",
                      "updateAt?": "0 | 1",
                      "city?": {
                        "_id?": "0 | 1",
                        "createAt?": "0 | 1",
                        "updateAt?": "0 | 1",
                        "name?": "0 | 1",
                        "enName?": "0 | 1",
                      },
                      "location?": "0 | 1",
                      "address?": "0 | 1",
                      "contact?": "0 | 1",
                      "postalCode?": "0 | 1",
                      "phoneNumber?": "0 | 1",
                      "email?": "0 | 1",
                      "gender?": "0 | 1",
                      "birthDate?": "0 | 1",
                      "nationalIdCardUrl?": "0 | 1",
                      "ssn?": "0 | 1",
                      "photoUrl?": "0 | 1",
                      "firstName?": "0 | 1",
                      "lastName?": "0 | 1",
                      "devices?": "0 | 1",
                      "password?": "0 | 1",
                      "isActive?": "0 | 1",
                      "authority?": {
                        "isMasterRole?": "0 | 1",
                      },
                      "notices?": {
                        "_id?": "0 | 1",
                        "createAt?": "0 | 1",
                        "updateAt?": "0 | 1",
                        "title?": "0 | 1",
                        "lead?": "0 | 1",
                        "text?": "0 | 1",
                        "pic?": "0 | 1",
                        "files?": "0 | 1",
                      },
                    },
                    "city?": {
                      "_id?": "0 | 1",
                      "createAt?": "0 | 1",
                      "updateAt?": "0 | 1",
                      "name?": "0 | 1",
                      "enName?": "0 | 1",
                      "state?": {
                        "_id?": "0 | 1",
                        "createAt?": "0 | 1",
                        "updateAt?": "0 | 1",
                        "name?": "0 | 1",
                        "enName?": "0 | 1",
                      },
                      "universities?": {
                        "_id?": "0 | 1",
                        "createAt?": "0 | 1",
                        "updateAt?": "0 | 1",
                        "name?": "0 | 1",
                        "organizations?": {
                          "acceptedByOrgHeadNumber?": "0 | 1",
                          "rejectedByOrgHeadNumber?": "0 | 1",
                          "pendingInOrgHeadNumber?": "0 | 1",
                          "_id?": "0 | 1",
                          "createAt?": "0 | 1",
                          "updateAt?": "0 | 1",
                          "location?": "0 | 1",
                          "address?": "0 | 1",
                          "contact?": "0 | 1",
                          "postalCode?": "0 | 1",
                          "logoUrl?": "0 | 1",
                          "name?": "0 | 1",
                        },
                        "universityHead?": {
                          "_id?": "0 | 1",
                          "createAt?": "0 | 1",
                          "updateAt?": "0 | 1",
                          "location?": "0 | 1",
                          "address?": "0 | 1",
                          "contact?": "0 | 1",
                          "postalCode?": "0 | 1",
                          "phoneNumber?": "0 | 1",
                          "email?": "0 | 1",
                          "gender?": "0 | 1",
                          "birthDate?": "0 | 1",
                          "nationalIdCardUrl?": "0 | 1",
                          "ssn?": "0 | 1",
                          "photoUrl?": "0 | 1",
                          "firstName?": "0 | 1",
                          "lastName?": "0 | 1",
                          "devices?": "0 | 1",
                          "password?": "0 | 1",
                          "isActive?": "0 | 1",
                        },
                        "city?": {
                          "_id?": "0 | 1",
                          "createAt?": "0 | 1",
                          "updateAt?": "0 | 1",
                          "name?": "0 | 1",
                          "enName?": "0 | 1",
                        },
                      },
                      "stores?": {},
                      "organizations?": {
                        "acceptedByOrgHeadNumber?": "0 | 1",
                        "rejectedByOrgHeadNumber?": "0 | 1",
                        "pendingInOrgHeadNumber?": "0 | 1",
                        "_id?": "0 | 1",
                        "createAt?": "0 | 1",
                        "updateAt?": "0 | 1",
                        "location?": "0 | 1",
                        "address?": "0 | 1",
                        "contact?": "0 | 1",
                        "postalCode?": "0 | 1",
                        "logoUrl?": "0 | 1",
                        "name?": "0 | 1",
                      },
                    },
                  },
                  "country?": {
                    "_id?": "0 | 1",
                    "createAt?": "0 | 1",
                    "updateAt?": "0 | 1",
                    "name?": "0 | 1",
                    "enName?": "0 | 1",
                    "states?": {
                      "_id?": "0 | 1",
                      "createAt?": "0 | 1",
                      "updateAt?": "0 | 1",
                      "name?": "0 | 1",
                      "enName?": "0 | 1",
                    },
                  },
                },
              },
            },
          },
        },
      },
      State: {
        doits: {
          update: {
            details: {},
          },
          delete: {
            details: {},
          },
          create: {
            details: {},
          },
          get: {
            details: {},
          },
        },
      },
      WareGroup: {
        doits: {
          get: {
            details: {},
          },
          delete: {
            details: {},
          },
          create: {
            details: {},
          },
          update: {
            details: {},
          },
        },
      },
      WareModel: {
        doits: {
          get: {
            details: {},
          },
          update: {
            details: {},
          },
          delete: {
            details: {},
          },
          create: {
            details: {},
          },
        },
      },
      WareType: {
        doits: {
          get: {
            details: {},
          },
          update: {
            details: {},
          },
          delete: {
            details: {},
          },
          create: {
            details: {},
          },
        },
      },
      WareClass: {
        doits: {
          update: {
            details: {},
          },
          delete: {
            details: {},
          },
          create: {
            details: {},
          },
          get: {
            details: {},
          },
        },
      },
      User: {
        doits: {
          create: {
            details: {},
          },
          gets: {
            details: {},
          },
          login: {
            details: {},
          },
          loginRequest: {
            details: {},
          },
          addAuthority: {
            details: {},
          },
          update: {
            details: {},
          },
        },
      },
      Inventory: {
        doits: {
          delete: {
            details: {},
          },
          update: {
            details: {},
          },
          create: {
            details: {},
          },
        },
      },
      ReqAllowedWareModel: {
        doits: {
          set: {
            details: {},
          },
          apply: {
            details: {},
          },
        },
      },
    },
  },
};
